GRANT SELECT ON V_$OSSTAT TO system;
GRANT SELECT ON V_$SGA TO system;
GRANT SELECT ON V_$SESSION TO system;
GRANT SELECT ON V_$PROCESS TO system;
GRANT SELECT ON DBA_DATA_FILES TO system;
GRANT SELECT ON DBA_TABLESPACES TO system;
GRANT SELECT ON DBA_USERS TO system;
